question_data = [
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "medium",
        "question": "The HTML5 standard was published in 2014.",
        "correct_answer": "True",
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "medium",
        "question": "The first computer bug was formed by faulty wires.",
        "correct_answer": "False",
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "medium",
        "question": "FLAC stands for 'Free Lossless Audio Condenser'.",
        "correct_answer": "False",
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "medium",
        "question": "All program codes have to be compiled into an executable file in order to be run. This file can then be executed on any machine.",
        "correct_answer": "False",
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Linus Torvalds created Linux and Git.",
        "correct_answer": "True",
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The programming language 'Python' is based off a modified version of 'JavaScript'",
        "correct_answer": "False",
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "medium",
        "question": "AMD created the first consumer 64-bit processor.",
        "correct_answer": "True",
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "easy",
        "question": "'HTML' stands for Hypertext Markup Language.",
        "correct_answer": "True",
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In most programming languages, the operator ++ is equivalent to the statement '+= 1'.",
        "correct_answer": "True",
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "hard",
        "question": "The IBM PC used an Intel 8008 microprocessor clocked at 4.77 MHz and 8 kilobytes of memory.",
        "correct_answer": "False",
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Amazon acquired Twitch in August 2014 for $970 million dollars.",
        "correct_answer": "True",
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The song 'Megalovania' by Toby Fox made its third appearence in the 2015 RPG 'Undertale'.",
        "correct_answer": "True",
    },
    {
        "category": "Entertainment: Film",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The movie 'The Nightmare before Christmas' was all done with physical objects.",
        "correct_answer": "True",
    },
    {
        "category": "History",
        "type": "boolean",
        "difficulty": "medium",
        "question": "The first televised presidential debate was between Jimmy Carter and Gerald Ford.",
        "correct_answer": "False",
    },
    {
        "category": "History",
        "type": "boolean",
        "difficulty": "medium",
        "question": "The M41 Walker Bulldog remains in service in some countries to this day.",
        "correct_answer": "True",
    },
    {
        "category": "Politics",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The S in Harry S. Truman stands for 'Samuel'.",
        "correct_answer": "False",
    },
    {
        "category": "Geography",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Israel is 7 hours ahead of New York.",
        "correct_answer": "True",
    },
    {
        "category": "Science: Mathematics",
        "type": "boolean",
        "difficulty": "hard",
        "question": "The binary number '101001101' is equivalent to the Decimal number '334'",
        "correct_answer": "False",
    },
    {
        "category": "Entertainment: Music",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Ashley Frangipane performs under the stage name Halsey.",
        "correct_answer": "True",
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "easy",
        "question": "RAM stands for Random Access Memory.",
        "correct_answer": "True",
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In Kingdom Hearts the Paopu fruit is said to intertwine the destinies for two people forever.",
        "correct_answer": "True",
    },
    {
        "category": "Sports",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Tennis was once known as Racquetball.",
        "correct_answer": "False",
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The Sun rises from the North.",
        "correct_answer": "False",
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "easy",
        "question": "You can legally drink alcohol while driving in Mississippi.",
        "correct_answer": "True",
    },
    {
        "category": "Entertainment: Board Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The card game 'Munchkin' won the 2001 Origins Award for Best Traditional Card Game.",
        "correct_answer": "True",
    },
    {
        "category": "Science & Nature",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Scientists accidentally killed the once known world's oldest living creature, a mollusc, known to be aged as 507 years old.",
        "correct_answer": "True",
    },
    {
        "category": "Vehicles",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The full English name of the car manufacturer BMW is Bavarian Motor Works",
        "correct_answer": "True",
    },
    {
        "category": "Vehicles",
        "type": "boolean",
        "difficulty": "medium",
        "question": "When BMW was established in 1916, it was producing automobiles.",
        "correct_answer": "False",
    },
    {
        "category": "History",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The United States of America declared their independence from the British Empire on July 4th, 1776.",
        "correct_answer": "True",
    },
    {
        "category": "Entertainment: Books",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Stephen Chbosky wrote the book 'The Perks of Being A Wallflower'.",
        "correct_answer": "True",
    },
    {
        "category": "Animals",
        "type": "boolean",
        "difficulty": "easy",
        "question": "A flock of crows is known as a homicide.",
        "correct_answer": "False",
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "medium",
        "question": "In the game 'Subnautica', a 'Cave Crawler' will attack you.",
        "correct_answer": "True",
    },
    {
        "category": "Entertainment: Film",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In the original Star Wars trilogy, Alec Guinness provided the voice for Darth Vader.",
        "correct_answer": "False",
    },
    {
        "category": "Politics",
        "type": "boolean",
        "difficulty": "medium",
        "question": "George W. Bush lost the popular vote in the 2004 United States presidential election.",
        "correct_answer": "False",
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In Pok&eacute;mon, Bulbasaur is the only starter pokemon that is a Grass\/Poison type.",
        "correct_answer": "True",
    },
    {
        "category": "Entertainment: Film",
        "type": "boolean",
        "difficulty": "easy",
        "question": "George Lucas directed the entire original Star Wars trilogy.",
        "correct_answer": "False",
    },
    {
        "category": "Sports",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In association football, or soccer, a corner kick is when the game restarts after someone scores a goal.",
        "correct_answer": "False",
    },
    {
        "category": "Entertainment: Music",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Stevie Wonder's real name is Stevland Hardaway Morris.",
        "correct_answer": "True",
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "medium",
        "question": "In Rocket League, you can play Basketball.",
        "correct_answer": "True",
    },
    {
        "category": "Entertainment: Film",
        "type": "boolean",
        "difficulty": "easy",
        "question": "'Minions' was released on the June 10th, 2015.",
        "correct_answer": "False",
    },
    {
        "category": "History",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Adolf Hitler was accepted into the Vienna Academy of Fine Arts.",
        "correct_answer": "False",
    },
    {
        "category": "Politics",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Donald Trump won the popular vote in the 2016 United States presidential election.",
        "correct_answer": "False",
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "medium",
        "question": "In the video game 'Transistor', 'Red' is the name of the main character.",
        "correct_answer": "True",
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In Heroes of the Storm, the Cursed Hollow map gimmick requires players to kill the undead to curse the enemy team.",
        "correct_answer": "False",
    },
    {
        "category": "Entertainment: Japanese Anime & Manga",
        "type": "boolean",
        "difficulty": "medium",
        "question": "In 'JoJo's Bizarre Adventure', Father Enrico Pucchi uses a total of 3 stands in Part 6: Stone Ocean.",
        "correct_answer": "True",
    },
    {
        "category": "History",
        "type": "boolean",
        "difficulty": "hard",
        "question": "During the Winter War, the amount of Soviet Union soliders that died or went missing was five times more than Finland's.",
        "correct_answer": "True",
    },
    {
        "category": "Science: Mathematics",
        "type": "boolean",
        "difficulty": "hard",
        "question": "L'Hôpital was the mathematician who created the homonymous rule that uses derivatives to evaluate limits with indeterminations.",
        "correct_answer": "False",
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "medium",
        "question": "In 'Call Of Duty: World At War', the first appearance of the 'PPSH-41' in 'Zombies' was in the map 'Der Riese'.",
        "correct_answer": "False",
    },
    {
        "category": "Entertainment: Japanese Anime & Manga",
        "type": "boolean",
        "difficulty": "medium",
        "question": "In 'To Love-Ru: Darkness', Yami reveals her real name is Eve.",
        "correct_answer": "True",
    },
    {
        "category": "Animals",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Finnish Lapphund dogs were used for herding reindeer.",
        "correct_answer": "True",
    },
    {
        "category": "Geography",
        "type": "boolean",
        "difficulty": "easy",
        "question": "New Haven is the capital city of the state of Connecticut in the United States.",
        "correct_answer": "False",
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "hard",
        "question": "Spoon theory is a theory, utilizing 'Spoons' as a metaphor for energy they can use in a day.",
        "correct_answer": "True",
    },
    {
        "category": "Geography",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Nova Scotia is on the east coast of Canada.",
        "correct_answer": "True",
    },
    {
        "category": "History",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The United States of America was the first country to launch a man into space.",
        "correct_answer": "False",
    },
    {
        "category": "Sports",
        "type": "boolean",
        "difficulty": "medium",
        "question": "During Wimbledon, spectators in the grounds can buy the tennis balls that have been used in matches.",
        "correct_answer": "True",
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Francis Bacon died from a fatal case of pneumonia while he was attempting to preserve meat by stuffing a chicken with snow.",
        "correct_answer": "True",
    },
    {
        "category": "Art",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Venus of Willendorf is one of the earliest works of art, depicting the planets Mars and Venus embrace in the heavens at night.",
        "correct_answer": "False",
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "There are 2 player roles in Trouble in Terrorist Town.",
        "correct_answer": "False",
    },
    {
        "category": "History",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Franz Joseph I was the last emperor of Austria.",
        "correct_answer": "False",
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In the video game 'Splatoon', the playable characters were originally going to be rabbits instead of squids.",
        "correct_answer": "True",
    }
]